/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        int inputRolls = 4;
        assertEquals("Should return an array of the appropriate length",
                inputRolls, classUnderTest.roll(inputRolls).length);
    }
}
