/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

public class Library {


    public int[] roll(int numberOfRolls){

        int[] newArray = new int[numberOfRolls];
        for (int i = 0; i < newArray.length; i++){
            newArray[i] = (int) (Math.random() * 6);
        }

        return newArray;
    }


    public boolean containsDuplicates(int[] arrayToCheck){

        boolean duplicateFound = false;
        for (int i = 0; i < arrayToCheck.length; i++){

            for (int number : arrayToCheck ){
                if (number == arrayToCheck[i]){
                    duplicateFound = true;
                    break;
                }
            }

            if (duplicateFound){
                break;
            }
        }
        return duplicateFound;
    }

    
}
