/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

import java.net.Inet4Address;

public class Library {


    public int[] roll(int numberOfRolls){

        int[] newArray = new int[numberOfRolls];
        for (int i = 0; i < newArray.length; i++){
            newArray[i] = (int) (Math.random() * 6);
        }

        return newArray;
    }


    public boolean containsDuplicates(int[] arrayToCheck){

        boolean duplicateFound = false;
        for (int i = 0; i < arrayToCheck.length; i++){

            for (int j = 0; j < arrayToCheck.length; j++){
                if(i == j){
                    continue;
                } else if (arrayToCheck[j] == arrayToCheck[i]){
                    duplicateFound = true;
                    break;
                }
            }

            if (duplicateFound){
                break;
            }
        }
        return duplicateFound;
    }


    public int averageCalculator(int[] array){
        int total = 0;
        for(int number : array){
            total += number;
        }
        return (total / array.length);
    }


    public int[] lowestAverageArrayCalc(int[][] inputArrayOfArrays){

        int[] returnArray = inputArrayOfArrays[0];
        int lowScore = Integer.MAX_VALUE;

        for (int[] array : inputArrayOfArrays){
            int thisAverage = averageCalculator(array);
            if (thisAverage < lowScore){
                lowScore = thisAverage;
                returnArray = array;
            }

        }

        return returnArray;
    }


    public String analyzeWeatherData(int[][] weeklyMonthTemperatures){



        return "";
    }

}
